import 'package:flutter/material.dart';

class LocalizationService extends ChangeNotifier {
  Locale _locale = const Locale('en');

  Locale get locale => _locale;

  static const supportedLocales = [Locale('en'), Locale('sw')];

  void toggleLocale() {
    _locale = _locale.languageCode == 'en'
        ? const Locale('sw')
        : const Locale('en');
    notifyListeners();
  }

    void setLocale(Locale locale) {
        if (_locale == locale) return;
        _locale = locale;
        notifyListeners();
    }

  String t(String key) {
    final t = _translations[_locale.languageCode] ?? _translations['en']!;
    return t[key] ?? key;
  }

  static const Map<String, Map<String, String>> _translations = {
    'en': {
      'welcome_title': 'Welcome to FarmGenius',
      'login_email': 'Email Login',
      'login_phone': 'Phone Login',
      'email_label': 'Email',
      'password_label': 'Password',
      'login_button': 'Sign In',
      'send_otp': 'Send OTP',
      'verify_otp': 'Verify OTP',
      'reset_password': 'Reset Password',
      'owner_home': 'Owner Dashboard',
      'manager_home': 'Manager Dashboard',
      'staff_home': 'Staff Dashboard',
      'logout': 'Logout',
      'signup_title': 'Sign up',
      'confirm_password_label': 'Confirm Password',
      'create_account': 'Create account',
      'password_mismatch': 'Passwords do not match',
      'signup_success': 'Sign up successful — check email for confirmation',
      'signup_failed': 'Sign up failed',
      'role_label': 'Role',
      'role_owner': 'Owner',
      'role_manager': 'Manager',
      'role_staff': 'Staff',
      'phone_label': 'Phone (+255)',
      'otp_label': 'OTP',
      'verifying_for': 'Verifying for:',
      'otp_verify_failed': 'OTP verification failed',
      'otp_send_failed': 'Could not send OTP',
      'login_failed': 'Login failed',
      'reset_email_sent': 'Email sent',
      'reset_failed': 'Failed',
      'no_internet': 'No internet connection',
      'tasks_tab': 'Tasks',
      'anomalies_tab': 'Anomalies',
      'zones_tab': 'Zones',
      'task_summary': 'Task Summary',
      'pending': 'Pending',
      'awaiting_review': 'Awaiting Review',
      'overdue': 'Overdue',
      'ai_generated': 'AI-Generated',
      'recent_tasks': 'Recent Tasks',
      'anomaly_alert_summary': 'Anomaly Alert Summary',
      'total': 'Total',
      'high_severity': 'High Severity',
      'unresolved': 'Unresolved',
      'no_anomalies_message':
          'No anomalies detected.\nFarm is operating normally!',
      'no_zones_available': 'No zones available.',
      'unknown': 'Unknown',
      'hectares': 'hectares',
      'mark_in_progress': 'Mark In Progress',
      'cancel_task': 'Cancel Task',
      'task_updated': 'Task updated',
      'could_not_update_task': 'Could not update task',
      'resolve': 'Resolve',
      'anomaly_resolved': 'Anomaly marked as resolved',
      'could_not_resolve_anomaly': 'Could not resolve anomaly',
      'tasks_count': 'Tasks',
      'recent_daily_checks': 'Recent Daily Checks',
      'today': 'Today',
      'this_week': 'This Week',
      'all': 'All',
      'no_checks_submitted': 'No checks submitted yet.',
      'daily_check_created': 'Daily check created.',
      'daily_check_updated': 'Daily check updated.',
      'task_marked_completed': 'Task marked as completed.',
      'task_submitted_for_review':
          'Task submitted for manager review (four-eyes).',
      'task_marked_in_progress': 'Task marked as in progress.',
      'could_not_complete_task': 'Could not complete task',
      'error_loading_tasks': 'Error loading tasks',
      'retry': 'Retry',
      'no_tasks_assigned': 'No tasks assigned.\nGreat work!',
      'refresh': 'Refresh',
      'due': 'Due',
      'go_to_zone': 'Go to Zone',
      'complete': 'Complete',
      'open_in_maps': 'Open in Maps',
      'no_zone_location': 'No location available for this zone',
      'could_not_open_maps': 'Could not open Maps',
      'create_daily_check': 'Create daily check',
      'payroll_tab': 'Payroll',
      'payroll_monthly_engine': 'Monthly Wage Intelligence',
      'payroll_month': 'Month',
      'payroll_hourly_rate': 'Base hourly wage',
      'payroll_total_hours': 'Total logged effort',
      'payroll_total_wages': 'Total projected wages',
      'payroll_staff_breakdown': 'Staff wage breakdown',
      'payroll_no_data': 'No payroll data available.',
      'payroll_no_staff_rows': 'No staff rows for current month.',
      'payroll_collect_data_hint':
          'Ask staff to submit execution reports with effort, GPS, and photos.',
      'payroll_wage': 'Wage',
      'payroll_effort_hours': 'Effort',
      'payroll_tasks_done': 'Tasks',
      'payroll_evidence': 'Evidence',
      'payroll_issues': 'Issues',
      'payroll_teamwork': 'Teamwork',
      'payroll_accountability_score': 'Score',
      'payroll_ai_prompts': 'AI Proactive Prompts',
      'payroll_ai_all_good':
          'Great progress: no urgent payroll data gaps detected.',
      'ai_operations_brief': 'AI Operations Brief',
      'ai_questions_to_ask': 'Questions to Ask Today',
      'ai_missing_data_requests': 'Missing Data Requests',
      'briefing_tab': 'Briefing',
      'briefing_title': 'Daily AI Briefing Digest',
      'briefing_generated_at': 'Generated',
      'briefing_open_prompts': 'Open prompts',
      'briefing_priority_actions': 'Priority Actions',
      'briefing_followup_questions': 'Follow-up Questions',
      'briefing_payroll_risks': 'Payroll Risk Signals',
      'briefing_escalations': 'Auto-escalation Alerts',
      'briefing_escalation_settings': 'Escalation Settings',
      'briefing_escalation_thresholds':
          'Escalation thresholds (overdue / evidence)',
      'briefing_overdue_threshold_hours': 'Overdue threshold (hours)',
      'briefing_stalled_threshold_hours': 'Missing evidence threshold (hours)',
      'approve_completion': 'Approve Completion',
      'request_rework': 'Request Rework',
      'briefing_threshold_validation':
          'Please enter valid positive hour values.',
      'briefing_no_data': 'No briefing data available.',
      'cancel': 'Cancel',
      'save': 'Save',
      'execute_with_evidence': 'Execute + Evidence',
      'execute_task_title': 'Execute Task Report',
      'execution_notes_label': 'Execution notes',
      'execution_notes_required': 'Please enter execution notes.',
      'quantity_label': 'Quantity',
      'quantity_unit_label': 'Unit',
      'issue_type_label': 'Issue type',
      'issue_details_label': 'Issue details',
      'issue_details_required': 'Please provide issue details.',
      'issue_none': 'No issue',
      'issue_delay': 'Delay',
      'issue_input_shortage': 'Input shortage',
      'issue_disease_pest': 'Disease / pest',
      'issue_safety': 'Safety',
      'issue_other': 'Other',
      'photo_url_1_label': 'Photo URL 1 (optional)',
      'photo_url_2_label': 'Photo URL 2 (optional)',
      'capture_gps_checkin': 'Capture GPS check-in',
      'gps_checkin_required': 'GPS check-in is required before submit.',
      'gps_permission_required':
          'Location permission is required for GPS check-in.',
      'gps_capture_failed': 'GPS capture failed',
      'gps_not_captured': 'GPS not captured yet.',
      'gps_captured': 'GPS captured',
      'submit_execution_report': 'Submit report',
      'accountability_dashboard': 'Accountability Dashboard',
      'daily_effort': 'Daily Effort',
      'weekly_effort': 'Weekly Effort',
      'monthly_effort': 'Monthly Effort',
      'evidence_logs': 'Evidence logs',
      'issue_reports': 'Issue reports',
      'teamwork_mentions': 'Teamwork mentions',
      'effort_hours_label': 'Effort hours',
      'effort_hours_required': 'Enter valid effort hours (0-24).',
      'teamwork_with_label': 'Teamworked with (optional)',
    'submit': 'Submit',
    'in_progress': 'In Progress',
    'completed': 'Completed',
    'cancelled': 'Cancelled',
    'staff_submit_task_for_review': 'Submit task for review',
    'staff_execution_completed': 'Execution completed',
    'staff_could_not_update_task': 'Could not update task',
    'staff_could_not_submit_task': 'Could not submit task',
    'staff_my_tasks': 'My Tasks',
    'staff_start': 'Start',
    'staff_submit_review': 'Submit Review',
    'staff_daily_checks': 'Daily Checks',
    'staff_new_check': 'New Check',
    'staff_no_zone': 'No zone',
    'staff_today_assist_tips': 'Today Assist Tips',
    'staff_legacy': 'Legacy',
    'staff_dashboard_load_error': 'Could not load staff dashboard',
    'staff_no_tip_right_now': 'No tip right now',
    'staff_active_tasks': 'active tasks',
    'staff_tap_start_or_submit_review': 'Tap to start or submit for review',
    'staff_visible_checks': 'visible checks',
    'staff_create_filter_edit_checks': 'Create, filter, and edit checks',
    'staff_assist_tip': 'Assist Tip',
    'staff_readiness': 'readiness',
    'staff_tap_view_dedication': 'Tap to view dedication',
    'staff_evidence_items': 'Evidence items',
    'staff_view_evidence': 'View evidence',
    'staff_evidence_urls_title': 'Evidence URLs',
    'staff_no_evidence_available': 'No evidence URLs available for this check.',
    'staff_could_not_open_link': 'Could not open this link',
    'staff_receipt_photos': 'Receipt photos',
    'staff_animal_photos': 'Animal photos',
    'staff_plant_photos': 'Plant/crop photos',
    'staff_infrastructure_photos': 'Infrastructure photos',
    'staff_other_photos': 'Other photos',
            'owner_financial_load_error': 'Could not load financial dashboard',
            'owner_financial_overview': 'Real-time Financial Overview',
            'owner_month_income': 'Current Month Income',
            'owner_month_expenses': 'Current Month Expenses',
            'owner_month_net': 'Current Month Profit/Loss',
            'owner_ytd_net': 'Year-to-Date Net',
            'owner_budget_vs_actual': 'Budget vs Actual',
            'owner_budget': 'Budget',
            'owner_variance': 'Variance',
            'owner_revenue_tracking': 'Revenue Tracking',
            'owner_revenue_by_source': 'Revenue by Source',
            'owner_revenue_by_zone': 'Revenue by Zone',
            'owner_projected_revenue': 'Projected Revenue',
            'owner_expense_analytics': 'Expense Analytics',
            'owner_expense_by_category': 'Expenses by Category',
            'owner_expense_by_zone': 'Expenses by Zone',
            'owner_expense_by_task_type': 'Expenses by Task Type',
            'owner_zone_profitability': 'Profitability by Zone',
            'owner_revenue': 'Revenue',
            'owner_expenses': 'Expenses',
            'owner_biological_valuation': 'Biological Asset Valuation',
            'owner_livestock_value': 'Livestock Value',
            'owner_crop_value': 'Standing Crop Value',
            'owner_total_asset_value': 'Total Asset Value',
            'owner_insurance_valuation': 'Insurance Valuation',
            'owner_ai_insights': 'AI-Powered Financial Insights',
            'owner_ops_assist': 'Operations Assist System',
            'owner_readiness_score': 'Farm Readiness Score',
            'owner_recommended_actions': 'Recommended Actions',
            'owner_data_ownership': 'Data Entry Ownership',
            'owner_primary_role': 'Primary role',
            'owner_review_role': 'Review role',
            'owner_positive_impact': 'Positive impact',
            'assist_today_tip': 'Self-improving assist tip for today',
            'owner_monthly_report_title': 'Monthly Report Generator',
            'owner_daily_report': 'Daily report',
            'owner_weekly_report': 'Weekly report',
            'owner_monthly_report': 'Monthly report',
            'owner_report_period': 'Report period',
            'owner_report_generated_at': 'Generated at',
            'owner_preview_report': 'Preview report',
            'owner_share_whatsapp': 'Share to WhatsApp',
            'owner_copy_csv': 'Copy CSV',
            'owner_export_pdf': 'Export PDF',
            'owner_monthly_highlights': 'Monthly highlights',
            'owner_monthly_csv_copied': 'Monthly CSV copied to clipboard',
            'owner_whatsapp_not_available': 'WhatsApp is not available on this device',
            'owner_pdf_export_failed': 'Could not export/share PDF report',
    },
    'sw': {
      'welcome_title': 'Karibu FarmGenius',
      'login_email': 'Ingia kwa Barua Pepe',
      'login_phone': 'Ingia kwa Simu',
      'email_label': 'Barua pepe',
      'password_label': 'Nenosiri',
      'login_button': 'Ingia',
      'send_otp': 'Tuma OTP',
      'verify_otp': 'Thibitisha OTP',
      'reset_password': 'Weka upya nenosiri',
      'owner_home': 'Dashibodi ya Mmiliki',
      'manager_home': 'Dashibodi ya Meneja',
      'staff_home': 'Dashibodi ya Mfanyakazi',
      'logout': 'Toka',
      'signup_title': 'Sajili',
      'confirm_password_label': 'Thibitisha Nenosiri',
      'create_account': 'Tengeneza akaunti',
      'password_mismatch': 'Nenosiri hazifani',
      'signup_success':
          'Usajili umefanikiwa – angalia barua pepe kwa uthibitisho',
      'signup_failed': 'Usajili umeshindikana',
      'role_label': 'Jukumu',
      'role_owner': 'Mmiliki',
      'role_manager': 'Meneja',
      'role_staff': 'Mfanyakazi',
      'phone_label': 'Simu (+255)',
      'otp_label': 'OTP',
      'verifying_for': 'Inathibitisha kwa:',
      'otp_verify_failed': 'Uthibitisho wa OTP umeshindwa',
      'otp_send_failed': 'Haikuweza kutuma OTP',
      'login_failed': 'Imeshindwa kuingia',
      'reset_email_sent': 'Barua pepe imetumwa',
      'reset_failed': 'Imeshindwa',
      'no_internet': 'Hakuna muunganisho wa intaneti',
      'tasks_tab': 'Kazi',
      'anomalies_tab': 'Hitilafu',
      'zones_tab': 'Kanda',
      'task_summary': 'Muhtasari wa Kazi',
      'pending': 'Zinazosubiri',
      'awaiting_review': 'Zinasubiri Uthibitisho',
      'overdue': 'Zilizochelewa',
      'ai_generated': 'Zilizotengenezwa na AI',
      'recent_tasks': 'Kazi za Hivi Karibuni',
      'anomaly_alert_summary': 'Muhtasari wa Tahadhari za Hitilafu',
      'total': 'Jumla',
      'high_severity': 'Ukali wa Juu',
      'unresolved': 'Hazijatatuliwa',
      'no_anomalies_message':
          'Hakuna hitilafu zilizogunduliwa.\nShamba linafanya kazi kawaida!',
      'no_zones_available': 'Hakuna kanda zilizopo.',
      'unknown': 'Haijulikani',
      'hectares': 'hekta',
      'mark_in_progress': 'Weka Inaendelea',
      'cancel_task': 'Ghairi Kazi',
      'task_updated': 'Kazi imesasishwa',
      'could_not_update_task': 'Imeshindikana kusasisha kazi',
      'resolve': 'Tatua',
      'anomaly_resolved': 'Hitilafu imewekwa kuwa imetatuliwa',
      'could_not_resolve_anomaly': 'Imeshindikana kutatua hitilafu',
      'tasks_count': 'Kazi',
      'recent_daily_checks': 'Ukaguzi wa Hivi Karibuni',
      'today': 'Leo',
      'this_week': 'Wiki Hii',
      'all': 'Zote',
      'no_checks_submitted': 'Hakuna ukaguzi uliowasilishwa bado.',
      'daily_check_created': 'Ukaguzi wa siku umeundwa.',
      'daily_check_updated': 'Ukaguzi wa siku umesasishwa.',
      'task_marked_completed': 'Kazi imewekwa kuwa imekamilika.',
      'task_submitted_for_review':
          'Kazi imetumwa kwa mapitio ya meneja (macho manne).',
      'task_marked_in_progress': 'Kazi imewekwa inaendelea.',
      'could_not_complete_task': 'Imeshindikana kukamilisha kazi',
      'error_loading_tasks': 'Hitilafu kupakia kazi',
      'retry': 'Jaribu tena',
      'no_tasks_assigned': 'Hakuna kazi ulizopewa.\nKazi nzuri!',
      'refresh': 'Onyesha upya',
      'due': 'Mwisho',
      'go_to_zone': 'Nenda Kwenye Kanda',
      'complete': 'Kamilisha',
      'open_in_maps': 'Fungua Ramani',
      'no_zone_location': 'Hakuna eneo la kanda hii',
      'could_not_open_maps': 'Imeshindikana kufungua Ramani',
      'create_daily_check': 'Unda ukaguzi wa siku',
      'payroll_tab': 'Malipo',
      'payroll_monthly_engine': 'Uchanganuzi wa Mishahara ya Mwezi',
      'payroll_month': 'Mwezi',
      'payroll_hourly_rate': 'Kiwango cha saa',
      'payroll_total_hours': 'Jumla ya saa zilizorekodiwa',
      'payroll_total_wages': 'Jumla ya malipo yanayotarajiwa',
      'payroll_staff_breakdown': 'Mgawanyo wa malipo kwa wafanyakazi',
      'payroll_no_data': 'Hakuna data ya malipo.',
      'payroll_no_staff_rows': 'Hakuna taarifa za wafanyakazi mwezi huu.',
      'payroll_collect_data_hint':
          'Waombe wafanyakazi wawasilishe ripoti zenye juhudi, GPS na picha.',
      'payroll_wage': 'Malipo',
      'payroll_effort_hours': 'Juhudi',
      'payroll_tasks_done': 'Kazi',
      'payroll_evidence': 'Ushahidi',
      'payroll_issues': 'Matatizo',
      'payroll_teamwork': 'Ushirikiano',
      'payroll_accountability_score': 'Alama',
      'payroll_ai_prompts': 'Mapendekezo ya AI',
      'payroll_ai_all_good':
          'Maendeleo mazuri: hakuna pengo kubwa la data ya malipo.',
      'ai_operations_brief': 'Muhtasari wa Uendeshaji wa AI',
      'ai_questions_to_ask': 'Maswali ya Kuuliza Leo',
      'ai_missing_data_requests': 'Data Inayokosekana',
      'briefing_tab': 'Muhtasari',
      'briefing_title': 'Muhtasari wa Kila Siku wa AI',
      'briefing_generated_at': 'Imetengenezwa',
      'briefing_open_prompts': 'Vichocheo vilivyo wazi',
      'briefing_priority_actions': 'Hatua za Kipaumbele',
      'briefing_followup_questions': 'Maswali ya Ufuatiliaji',
      'briefing_payroll_risks': 'Hatari za Malipo',
      'briefing_escalations': 'Tahadhari za Kupandisha Kipaumbele',
      'briefing_escalation_settings': 'Mipangilio ya Kupandisha Kipaumbele',
      'briefing_escalation_thresholds':
          'Viwango vya tahadhari (kuchelewa / ushahidi)',
      'briefing_overdue_threshold_hours': 'Kiwango cha kuchelewa (saa)',
      'briefing_stalled_threshold_hours': 'Kiwango cha kukosa ushahidi (saa)',
      'approve_completion': 'Idhinisha Ukamilishaji',
      'request_rework': 'Rudisha Kazi Irekebishwe',
      'briefing_threshold_validation':
          'Tafadhali weka thamani sahihi ya saa zaidi ya sifuri.',
      'briefing_no_data': 'Hakuna data ya muhtasari.',
      'cancel': 'Ghairi',
      'save': 'Hifadhi',
      'execute_with_evidence': 'Tekeleza + Ushahidi',
      'execute_task_title': 'Ripoti ya Utekelezaji wa Kazi',
      'execution_notes_label': 'Maelezo ya utekelezaji',
      'execution_notes_required': 'Tafadhali weka maelezo ya utekelezaji.',
      'quantity_label': 'Kiasi',
      'quantity_unit_label': 'Kipimo',
      'issue_type_label': 'Aina ya tatizo',
      'issue_details_label': 'Maelezo ya tatizo',
      'issue_details_required': 'Tafadhali jaza maelezo ya tatizo.',
      'issue_none': 'Hakuna tatizo',
      'issue_delay': 'Kuchelewa',
      'issue_input_shortage': 'Upungufu wa pembejeo',
      'issue_disease_pest': 'Ugonjwa / wadudu',
      'issue_safety': 'Usalama',
      'issue_other': 'Nyingine',
      'photo_url_1_label': 'Kiungo cha picha 1 (si lazima)',
      'photo_url_2_label': 'Kiungo cha picha 2 (si lazima)',
      'capture_gps_checkin': 'Nasa GPS check-in',
      'gps_checkin_required': 'GPS check-in inahitajika kabla ya kutuma.',
      'gps_permission_required':
          'Ruhusa ya location inahitajika kwa GPS check-in.',
      'gps_capture_failed': 'Imeshindikana kunasa GPS',
      'gps_not_captured': 'GPS haijanaswa bado.',
      'gps_captured': 'GPS imenaswa',
      'submit_execution_report': 'Wasilisha ripoti',
      'accountability_dashboard': 'Dashibodi ya Uwajibikaji',
      'daily_effort': 'Juhudi za Leo',
      'weekly_effort': 'Juhudi za Wiki',
      'monthly_effort': 'Juhudi za Mwezi',
      'evidence_logs': 'Kumbukumbu za ushahidi',
      'issue_reports': 'Ripoti za matatizo',
      'teamwork_mentions': 'Ushirikiano uliotajwa',
      'effort_hours_label': 'Saa za juhudi',
      'effort_hours_required': 'Weka saa sahihi za juhudi (0-24).',
      'teamwork_with_label': 'Ulishirikiana na nani (si lazima)',
    'submit': 'Wasilisha',
    'in_progress': 'Inaendelea',
    'completed': 'Imekamilika',
    'cancelled': 'Imeghairiwa',
    'staff_submit_task_for_review': 'Wasilisha kazi kwa mapitio',
    'staff_execution_completed': 'Utekelezaji umekamilika',
    'staff_could_not_update_task': 'Imeshindikana kusasisha kazi',
    'staff_could_not_submit_task': 'Imeshindikana kuwasilisha kazi',
    'staff_my_tasks': 'Kazi Zangu',
    'staff_start': 'Anza',
    'staff_submit_review': 'Wasilisha kwa Mapitio',
    'staff_daily_checks': 'Ukaguzi wa Kila Siku',
    'staff_new_check': 'Ukaguzi Mpya',
    'staff_no_zone': 'Hakuna kanda',
    'staff_today_assist_tips': 'Vidokezo vya Usaidizi vya Leo',
    'staff_legacy': 'Urithi',
    'staff_dashboard_load_error': 'Imeshindikana kupakia dashibodi ya mfanyakazi',
    'staff_no_tip_right_now': 'Hakuna kidokezo kwa sasa',
    'staff_active_tasks': 'kazi zinazofanya kazi',
    'staff_tap_start_or_submit_review': 'Gusa kuanza au kuwasilisha kwa mapitio',
    'staff_visible_checks': 'ukaguzi unaoonekana',
    'staff_create_filter_edit_checks': 'Unda, chuja, na hariri ukaguzi',
    'staff_assist_tip': 'Kidokezo cha Usaidizi',
    'staff_readiness': 'utayari',
    'staff_tap_view_dedication': 'Gusa kuona heshima ya kumbukumbu',
    'staff_evidence_items': 'Vipengele vya ushahidi',
    'staff_view_evidence': 'Tazama ushahidi',
    'staff_evidence_urls_title': 'Viungo vya Ushahidi',
    'staff_no_evidence_available': 'Hakuna viungo vya ushahidi kwa ukaguzi huu.',
    'staff_could_not_open_link': 'Imeshindikana kufungua kiungo hiki',
    'staff_receipt_photos': 'Picha za risiti',
    'staff_animal_photos': 'Picha za wanyama',
    'staff_plant_photos': 'Picha za mimea/mazao',
    'staff_infrastructure_photos': 'Picha za miundombinu',
    'staff_other_photos': 'Picha zingine',
            'owner_financial_load_error': 'Imeshindikana kupakia dashibodi ya fedha',
            'owner_financial_overview': 'Muhtasari wa Fedha wa Wakati Halisi',
            'owner_month_income': 'Mapato ya Mwezi Huu',
            'owner_month_expenses': 'Matumizi ya Mwezi Huu',
            'owner_month_net': 'Faida/Hasara ya Mwezi Huu',
            'owner_ytd_net': 'Jumla Halisi ya Mwaka Hadi Sasa',
            'owner_budget_vs_actual': 'Bajeti dhidi ya Halisi',
            'owner_budget': 'Bajeti',
            'owner_variance': 'Tofauti',
            'owner_revenue_tracking': 'Ufuatiliaji wa Mapato',
            'owner_revenue_by_source': 'Mapato kwa Chanzo',
            'owner_revenue_by_zone': 'Mapato kwa Kanda',
            'owner_projected_revenue': 'Mapato Yanayotarajiwa',
            'owner_expense_analytics': 'Uchanganuzi wa Matumizi',
            'owner_expense_by_category': 'Matumizi kwa Kategoria',
            'owner_expense_by_zone': 'Matumizi kwa Kanda',
            'owner_expense_by_task_type': 'Matumizi kwa Aina ya Kazi',
            'owner_zone_profitability': 'Faida kwa Kanda',
            'owner_revenue': 'Mapato',
            'owner_expenses': 'Matumizi',
            'owner_biological_valuation': 'Thamani ya Mali Hai',
            'owner_livestock_value': 'Thamani ya Mifugo',
            'owner_crop_value': 'Thamani ya Mazao Shambani',
            'owner_total_asset_value': 'Jumla ya Thamani ya Mali',
            'owner_insurance_valuation': 'Thamani ya Bima',
            'owner_ai_insights': 'Maarifa ya Fedha ya AI',
            'owner_ops_assist': 'Mfumo wa Usaidizi wa Uendeshaji',
            'owner_readiness_score': 'Alama ya Utayari wa Shamba',
            'owner_recommended_actions': 'Hatua Zinazopendekezwa',
            'owner_data_ownership': 'Umiliki wa Uingizaji wa Data',
            'owner_primary_role': 'Jukumu kuu',
            'owner_review_role': 'Jukumu la ukaguzi',
            'owner_positive_impact': 'Athari chanya',
            'assist_today_tip': 'Kidokezo cha leo kutoka mfumo unaojiboresha',
            'owner_monthly_report_title': 'Mzalishaji wa Ripoti ya Mwezi',
            'owner_daily_report': 'Ripoti ya siku',
            'owner_weekly_report': 'Ripoti ya wiki',
            'owner_monthly_report': 'Ripoti ya mwezi',
            'owner_report_period': 'Kipindi cha ripoti',
            'owner_report_generated_at': 'Imetengenezwa saa',
            'owner_preview_report': 'Angalia ripoti',
            'owner_share_whatsapp': 'Tuma WhatsApp',
            'owner_copy_csv': 'Nakili CSV',
            'owner_export_pdf': 'Toa PDF',
            'owner_monthly_highlights': 'Mambo muhimu ya mwezi',
            'owner_monthly_csv_copied': 'CSV ya mwezi imenakiliwa',
            'owner_whatsapp_not_available': 'WhatsApp haipatikani kwenye kifaa hiki',
            'owner_pdf_export_failed': 'Imeshindikana kutoa/kushiriki ripoti ya PDF',
    },
  };
}
